version: '3.9'

services:
  mariadb:
    image: mariadb
    container_name: db_brisq
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Pa$$w0rd
      - MYSQL_PASSWORD=Pa$$w0rd
      - MYSQL_USER=brisq
      - MYSQL_DATABASE=brisq_db

  api:
    build:
      context: ./
      dockerfile: ./api.dockerfile
    container_name: api_brisq
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - mariadb
    command: sh -c "npm run start"
