name: Pull new Docker image from dev server

on:
  workflow_run:
    workflows: 
      - "Create and publish a Docker image"
    branches: [main]
    types: 
      - completed
    
jobs:

  pull-image:
    name: Pull new image from server
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /opt/brisq-core_dev/
          docker-compose pull
          docker-compose up -d
          echo "pull works" > ~/works-core
