name: Pull new Docker image from dev server

on:
  workflow_run:
    workflows: 
      - "Create and publish a Docker image"
    branches: [master]
    types: 
      - completed
    
jobs:

  pull-image:
    name: Pull new image from server
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          docker stop brisq-core_dev_app_1
          docker rm brisq-core_dev_app_1
          docker rmi ghcr.io/brisqapp/brisq-core:master
          docker pull ghcr.io/brisqapp/brisq-core:master
          docker run -d -p 8080:8080 --name brisq-core_dev_app_1 --network brisq-core_dev_default ghcr.io/brisqapp/brisq-core:master
          echo "pull works" > ~/works
